#ifndef __BASE_HEADERS__
#define __BASE_HEADERS__
#include <string> 
#include <stdio.h>
#include <typeinfo>
#include <iostream>
#include <cassert>
#include <set>
#include <list>
#include <typeinfo>
#include "_log.hpp"
#include "SqClass.h"
#include "typedef.hpp"
#include "uid_and_chk.hpp"
#include "serialiser.hpp"
#include "memmgr.hpp"
#include "utils.hpp"
#include "dbquery.hpp"
#include "sql/sqlcmdType.hpp"
#include "sql/insert.hpp"
#include "sql/update.hpp"
#include "sql/drop.hpp"
#include "sql/selectAndJoin.hpp"
#include "sql/sqlGenerator.hpp"
#include "sql/sqlcopy.hpp"
#include "data_and_structs.hpp"
#include <boost/asio.hpp>
#include <boost/bind/bind.hpp>
#include <boost/smart_ptr.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <boost/uuid/random_generator.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <boost/filesystem.hpp>
#include <sys/stat.h>
#endif