#ifndef __BASE_HEADERS__
#define __BASE_HEADERS__
#include <string> 
#include <stdio.h>
#include <typeinfo>
#include <iostream>
#include <cassert>
#include <set>
#include <list>
#include <typeinfo>
#include "log/_log.hpp"
#include "sql/SqClass.h"
#include "DA/typedef.hpp"
#include "uid_and_chk.hpp"
#include "blocks/serialiser.hpp"
#include "cache/memmgr.hpp"
#include "blocks/utils/utils.hpp"
#include "blocks/dbqueries.hpp"
#include "sql/sqlcmdType.hpp"
#include "sql/insert.hpp"
#include "sql/update.hpp"
#include "sql/drop.hpp"
#include "sql/selectAndJoin.hpp"
#include "sql/sqlGenerator.hpp"
#include "sql/sqlcopy.hpp"
#include <boost/asio.hpp>
#include <boost/bind/bind.hpp>
#include <boost/smart_ptr.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <boost/uuid/random_generator.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <boost/filesystem.hpp>
#include <sys/stat.h>
#endif